### ISSUE TITLE
Can't load this with ESM

### ISSUE THREAD

**Issue by richtera** [DZakh/rescript-envsafe#1]
I was tying to import this module using nodejs using ESM and it gives and error because the "type": "module" annotation inside of the package.json is missing. Not quite sure how many modules inside of the rescript ecosystem have this problem, but with nodejs I was not having much luck switching to module: es6.

**Comment by DZakh** [comment]
To solve the problem you should change the output suffix to `.res.mjs`

**Comment by richtera** [comment]
Hmm but these are deployment files, right? Or does the rescript compiler dynamically write new files into the node_modules folders with new file extensions?

**Comment by DZakh** [comment]
Sorry, for the long reply, I was on vacation and didn't touch my laptop for the whole week 😁

> Or does the rescript compiler dynamically write new files into the node_modules folders with new file extensions?

The answer is yes.

**Comment by richtera** [comment]
Ok I will test that, usually npms are installed and then just used and not part of the rescript compile, because during the rescript compile we install development npms and during deployment just production npms which precludes rescript. Not quite sure how this should work, but I guess you would be forced to install all development npms.
